### ISSUE TITLE
Can jest-extend matchers be used with Playwright test runner?

### ISSUE THREAD

**Issue by HilaryGreen** [jest-community/jest-extended#459]
**Feature Request**

Description: Use jest-extend matchers with Playwright test runner

Possible solution:
I really like some of your matchers (one example OneOfMany with array of accepable results) and used serveral when I was developing Playwright tests using Jest as the test runner.
Now I want to switch to the Playwright test runner, but the matchers available do not cover these so well. Is it possible to use the jest-extend matchers without using Jest somehow? (My tests are in Typescript)

Regards
Hilary

**Comment by keeganwitt** [comment]
I'm not familiar with Playwright, but it should be possible to use Playwright + Jest + Jest Extended. However, I'm fairly certain it would _not_ be possible to use Playwright + Jest Extended without Jest. Why? Because Jest Extended provides matchers for Jest to use. So, unless Playwright has an API compatible implementation of the Matcher interface, I don't see how Jest Extended's additional matchers would be usable.
